In [4]:
import pandas as pd

df = pd.read_csv("../data/irrigation_prediction.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (10000, 20)

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [5]:
print("Columns:")
print(df.columns.tolist())

Columns:
['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon', 'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm', 'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage', 'Season', 'Irrigation_Type', 'Water_Source', 'Field_Area_hectare', 'Mulching_Used', 'Previous_Irrigation_mm', 'Region', 'Irrigation_Need']

In [6]:
print("\nData types:")
print(df.dtypes)

Data types:
Soil_Type                      str
Soil_pH                    float64
Soil_Moisture              float64
Organic_Carbon             float64
Electrical_Conductivity    float64
Temperature_C              float64
Humidity                   float64
Rainfall_mm                float64
Sunlight_Hours             float64
Wind_Speed_kmh             float64
Crop_Type                      str
Crop_Growth_Stage              str
Season                         str
Irrigation_Type                str
Water_Source                   str
Field_Area_hectare         float64
Mulching_Used                  str
Previous_Irrigation_mm     float64
Region                         str
Irrigation_Need                str
dtype: object

In [7]:
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  str
 14  Water_Source             10000 non-null  str
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  str
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  str
 19  Irrigation_Need          10000 non-null  str
dtypes: float64(11), str(9)
memory usage: 1.5 MB

In [8]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
Irrigation_Need            0
dtype: int64

In [9]:
print("\nDuplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0

In [10]:
print("\nStatistical summary:")
df.describe(include="all")

Statistical summary:

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000,10000,10000,10000,10000,10000.000000,10000,10000.000000,10000,10000
unique,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,4,3,4,4,NaN,2,NaN,5,3
top,Sandy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rice,Harvest,Rabi,Sprinkler,River,NaN,No,NaN,South,Low
freq,2536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1711,2581,3383,2527,2528,NaN,5013,NaN,2102,5864
mean,NaN,6.487857,36.969207,0.944731,1.791963,26.991423,60.080339,1252.499420,7.518538,10.163545,NaN,NaN,NaN,NaN,NaN,7.598024,NaN,59.864122,NaN,NaN
std,NaN,0.979963,16.430845,0.372406,0.984202,8.664074,20.187973,715.582201,2.016077,5.670923,NaN,NaN,NaN,NaN,NaN,4.233919,NaN,34.483722,NaN,NaN
min,NaN,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,NaN,NaN,NaN,NaN,NaN,0.300000,NaN,0.020000,NaN,NaN
25%,NaN,5.640000,22.860000,0.620000,0.940000,19.460000,42.855000,634.155000,5.760000,5.160000,NaN,NaN,NaN,NaN,NaN,3.950000,NaN,30.160000,NaN,NaN
50%,NaN,6.470000,37.240000,0.950000,1.780000,27.090000,60.040000,1250.335000,7.560000,10.190000,NaN,NaN,NaN,NaN,NaN,7.540000,NaN,59.630000,NaN,NaN
75%,NaN,7.350000,50.940000,1.260000,2.650000,34.500000,77.705000,1880.265000,9.260000,15.100000,NaN,NaN,NaN,NaN,NaN,11.202500,NaN,90.030000,NaN,NaN
max,NaN,8.200000,65.000000,1.600000,3.500000,42.000000,95.000000,2499.690000,11.000000,20.000000,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,119.990000,NaN,NaN

In [11]:
for column in df.columns:
    print(column)

Soil_Type
Soil_pH
Soil_Moisture
Organic_Carbon
Electrical_Conductivity
Temperature_C
Humidity
Rainfall_mm
Sunlight_Hours
Wind_Speed_kmh
Crop_Type
Crop_Growth_Stage
Season
Irrigation_Type
Water_Source
Field_Area_hectare
Mulching_Used
Previous_Irrigation_mm
Region
Irrigation_Need